name: ramp-scMARK-classification
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - scipy
  - numpy
  - pandas
  - jupyterlab
  # https://github.com/scverse/scanpy/issues/2411
  - matplotlib<3.7 
  - seaborn
  - scikit-learn

  # dev
  - flake8
  - black


  - pip
  - pip:
    - osfclient
    - ramp-workflow
    - scanpy 
